spring:
  application:
    name:
      libraryManagementSystem

  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8000


